//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OHD_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtracurricularRegistration
    {
        public int RegistrationID { get; set; }
        public int ActivityID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ExtracurricularActivity ExtracurricularActivity { get; set; }
        public virtual User User { get; set; }
    }
}
