//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OHD_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestAttachment
    {
        public int AttachmentID { get; set; }
        public int RequestID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
